spring.datasource.url: jdbc:mysql://localhost:3306/testov?useSSL=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: Ckjy@Gbhfa347
spring.jpa.hibernate.ddl-auto: update

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect







